### ISSUE TITLE
Moodle cron job not working

### ISSUE THREAD

**Issue by giangduong** [ubc/moodle-docker#13]
I got this notification

<img width="633" alt="image" src="https://user-images.githubusercontent.com/8393739/227085674-fdba6ed0-d122-48d5-9a85-08015299005d.png">

Do you have any ideas to fix this?

Thanks in advance!

**Comment by xcompass** [comment]
You will need to setup cron job to run it. You can refer to this page: https://docs.moodle.org/401/en/Cron

Depending on your environment, you may need to setup a cronjob on your host and run something like `docker exec -it moodle php admin/cli/cron.php`. Or this (https://github.com/ubc/charts/blob/master/moodle/templates/cronjob.yaml) for k8s.

**Comment by giangduong** [comment]
This solution "docker exec -it moodle php admin/cli/cron.php" seems to work but i got another issue.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/8393739/227405383-4d4b97f9-13d5-4878-bcf1-e8a19c36563e.png">

I check PHP info. Everything looks ok.

<img width="977" alt="image" src="https://user-images.githubusercontent.com/8393739/227405699-96eb131c-6d70-4f8f-bf37-d6e30a7fe0ce.png">

What should cause this problem?

**Comment by xcompass** [comment]
Is this when you run `cron.php` or somewhere else?

**Comment by giangduong** [comment]
Sorry. Never mind. It works fine with your image. The problem happens with my custom Dockerfile.

Thanks alot for your support.
