### ISSUE TITLE
Impossible to use PostgreSQL

### ISSUE THREAD

**Issue by newlukai** [ubc/moodle-docker#6]
To use a PostgreSQL database, Moodle wants to read `pgsql` in its configuration file (`$CFG->dbtype`). Unfortunately, the environment variable `MOODLE_DB_TYPE` is used to set this configuration value. Which the `docker-entrypoint.sh` expects to be `postgres` if one wants to use PostgreSQL.

**Comment by xcompass** [comment]
closed by #7
